export const _CONSTANTS = {
  RESPONSE_CODE: {
    DATA_VALIDATION_ERROR: 400,
    SERVICE_VALIDATION_ERROR: 401,
    SERVICE_ERROR: 500,
  },
  DATA: {
    DATA_EXISTS: 'DUPLICATE DATA',
    CREATED_SUCCESSFULLY: 'ADMIN CREATED SUCCESSFULLY',
  }
} as const;
